SELECT * FROM DINASTIA;
SELECT * FROM DINASTIA_TIENE_NOMBRE;
SELECT * FROM MONARCA;
SELECT * FROM MONARCA_REINA_REINO;
SELECT * FROM REINO;
SELECT COUNT(*) FROM MONARCA WHERE NOMBRE = "LEONOR" AND NOMBRE_DINASTIA = "ARAGÓN";

SELECT ID_MONARCA FROM MONARCA_REINA_REINO WHERE ID_REINO = 11;

SELECT REINO.ID_MONARCA FROM MONARCA_REINA_REINO MRR JOIN REINO ON MRR.ID_REINO=REINO.ID_REINO WHERE REINO.ID_MONARCA = 8;